// <auto-generated />
using System;
using MercadoCapitales.API.Clientes.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Clientes.Migrations
{
    [DbContext(typeof(ContextCliente))]
    [Migration("20241231210536_VERSION11")]
    partial class VERSION11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Cliente", b =>
                {
                    b.Property<Guid?>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRecovery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.ClienteEncuestas", b =>
                {
                    b.Property<Guid?>("ClienteEncuestasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClieKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EncuestaRespuesta")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClienteEncuestasId");

                    b.ToTable("ClienteEncuestas");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.ClientePerfilInversor", b =>
                {
                    b.Property<Guid?>("ClientePerfilInversorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncuestaRespuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientePerfilInversorId");

                    b.ToTable("ClientePerfilInversor");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.EncuestaPregunta", b =>
                {
                    b.Property<Guid?>("EncuestaPreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncuestaPreguntaId");

                    b.ToTable("EncuestaPregunta");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.EncuestaRespuesta", b =>
                {
                    b.Property<Guid?>("EncuestaRespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncuestaPreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoInput")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncuestaRespuestaId");

                    b.HasIndex("EncuestaPreguntaId");

                    b.ToTable("EncuestaRespuesta");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SettType")
                        .HasColumnType("int");

                    b.Property<string>("SymbolReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Login", b =>
                {
                    b.Property<Guid?>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuySize")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrimaryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellSize")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDailyDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradingSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryUserId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.PrimaryUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("PrimaryUser");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.EncuestaRespuesta", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Modelo.EncuestaPregunta", null)
                        .WithMany("encuestaRespuestas")
                        .HasForeignKey("EncuestaPreguntaId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Instrument", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Modelo.Position", "Position")
                        .WithOne("Instrument")
                        .HasForeignKey("MercadoCapitales.API.Clientes.Modelo.Instrument", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Login", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Modelo.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.Position", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Modelo.PrimaryUser", "PrimaryUser")
                        .WithMany("Positions")
                        .HasForeignKey("PrimaryUserId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Modelo.PrimaryUser", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Modelo.Cliente", "Cliente")
                        .WithMany("PrimaryUsers")
                        .HasForeignKey("ClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
