// <auto-generated />
using System;
using MercadoCapitales.API.Clientes.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Clientes.Migrations
{
    [DbContext(typeof(ContextCliente))]
    [Migration("20250201202038_VERSION18")]
    partial class VERSION18
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.AccountExecutive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Organization")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("Recommender")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AccountExecutive");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Cliente", b =>
                {
                    b.Property<Guid?>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRecovery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.ClienteEncuestas", b =>
                {
                    b.Property<Guid?>("ClienteEncuestasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClieKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EncuestaRespuesta")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClienteEncuestasId");

                    b.ToTable("ClienteEncuestas");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.ClientePerfilInversor", b =>
                {
                    b.Property<Guid?>("ClientePerfilInversorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncuestaRespuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientePerfilInversorId");

                    b.ToTable("ClientePerfilInversor");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.EncuestaPregunta", b =>
                {
                    b.Property<Guid?>("EncuestaPreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncuestaPreguntaId");

                    b.ToTable("EncuestaPregunta");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.EncuestaRespuesta", b =>
                {
                    b.Property<Guid?>("EncuestaRespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncuestaPreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoInput")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncuestaRespuestaId");

                    b.HasIndex("EncuestaPreguntaId");

                    b.ToTable("EncuestaRespuesta");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.InvestmentRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("InvestmentRecommendation");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Login", b =>
                {
                    b.Property<Guid?>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuySize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDailyDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradingSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryUserId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.PrimaryUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("PrimaryUser");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountExecutiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountExecutiveId");

                    b.ToTable("Recommendation");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.EncuestaRespuesta", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.EncuestaPregunta", null)
                        .WithMany("encuestaRespuestas")
                        .HasForeignKey("EncuestaPreguntaId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.InvestmentRecommendation", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.Recommendation", "Recommendation")
                        .WithMany("InvestmentRecommendation")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Login", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Position", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.PrimaryUser", "PrimaryUser")
                        .WithMany("Positions")
                        .HasForeignKey("PrimaryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.PrimaryUser", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.Cliente", "Cliente")
                        .WithMany("PrimaryUsers")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Clientes.Models.Recommendation", b =>
                {
                    b.HasOne("MercadoCapitales.API.Clientes.Models.AccountExecutive", "AccountExecutive")
                        .WithMany("Recommendations")
                        .HasForeignKey("AccountExecutiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
