// <auto-generated />
using System;
using MercadoCapitales.API.Especies.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Especies.Migrations
{
    [DbContext(typeof(ContextEspecie))]
    [Migration("20230116210715_TipoPanelPrecioV0")]
    partial class TipoPanelPrecioV0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.InstrumentOrderType", b =>
                {
                    b.Property<Guid?>("InstrumentOrderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstrumentOrderTypeId");

                    b.ToTable("InstrumentOrderType");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.InstrumentTimeInForce", b =>
                {
                    b.Property<Guid?>("InstrumentTimesInForceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstrumentTimesInForceId");

                    b.ToTable("InstrumentTimeInForce");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.Instrumento", b =>
                {
                    b.Property<Guid?>("InstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketSegmentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("PriceConversionFactor")
                        .HasColumnType("real");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cficode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("contractMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("highLimitPrice")
                        .HasColumnType("real");

                    b.Property<string>("instrumentPricePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instrumentSizePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lowLimitPrice")
                        .HasColumnType("real");

                    b.Property<string>("marketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("maxTradeVol")
                        .HasColumnType("real");

                    b.Property<float>("minPriceIncrement")
                        .HasColumnType("real");

                    b.Property<float>("minTradeVol")
                        .HasColumnType("real");

                    b.Property<float>("roundLot")
                        .HasColumnType("real");

                    b.Property<string>("securityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("securityIdSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("securityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("settlType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("tickSize")
                        .HasColumnType("real");

                    b.HasKey("InstrumentoId");

                    b.ToTable("Instrumento");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.ProductGroup", b =>
                {
                    b.Property<Guid?>("ProductGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mercado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductGroupId");

                    b.ToTable("ProductGroup");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.TipoPanelPrecio", b =>
                {
                    b.Property<Guid?>("TipoPanelPrecioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cficode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marketSegmentId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPanelPrecioId");

                    b.ToTable("TipoPanelPrecio");
                });
#pragma warning restore 612, 618
        }
    }
}
