// <auto-generated />
using System;
using MercadoCapitales.API.Especies.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Especies.Migrations
{
    [DbContext(typeof(ContextEspecie))]
    [Migration("20230110215406_MigracionInicialV0")]
    partial class MigracionInicialV0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Especies.Modelo.Instrumento", b =>
                {
                    b.Property<Guid?>("InstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NestedMarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NestedSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstrumentoId");

                    b.ToTable("Instrumento");
                });
#pragma warning restore 612, 618
        }
    }
}
