// <auto-generated />
using System;
using MercadoCapitales.API.Especies.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Especies.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250124194801_VERSION9")]
    partial class VERSION9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Especies.Models.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketSegmentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("PriceConversionFactor")
                        .HasColumnType("real");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cficode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("contractMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("highLimitPrice")
                        .HasColumnType("real");

                    b.Property<string>("instrumentPricePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instrumentSizePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("lowLimitPrice")
                        .HasColumnType("real");

                    b.Property<string>("marketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("maxTradeVol")
                        .HasColumnType("real");

                    b.Property<float>("minPriceIncrement")
                        .HasColumnType("real");

                    b.Property<float>("minTradeVol")
                        .HasColumnType("real");

                    b.Property<float>("roundLot")
                        .HasColumnType("real");

                    b.Property<string>("securityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("securityIdSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("securityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("settlType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("tickSize")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Models.InstrumentOrderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("InstrumentOrderType");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Models.InstrumentTimeInForce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("InstrumentTimeInForce");
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Models.InstrumentOrderType", b =>
                {
                    b.HasOne("MercadoCapitales.API.Especies.Models.Instrument", "Instrument")
                        .WithMany("InstrumentOrderType")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Especies.Models.InstrumentTimeInForce", b =>
                {
                    b.HasOne("MercadoCapitales.API.Especies.Models.Instrument", "Instrument")
                        .WithMany("InstrumentTimeInForce")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
