// <auto-generated />
using System;
using MercadoCapitales.API.Precios.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Precios.Migrations
{
    [DbContext(typeof(ContextPrecio))]
    [Migration("20221227190541_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Precios.Modelo.CotizacionAccion", b =>
                {
                    b.Property<Guid?>("PrecioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ajuste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CCompra")
                        .HasColumnType("real");

                    b.Property<float?>("CVenta")
                        .HasColumnType("real");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Max")
                        .HasColumnType("real");

                    b.Property<float?>("Min")
                        .HasColumnType("real");

                    b.Property<float?>("Monto")
                        .HasColumnType("real");

                    b.Property<int?>("Oper")
                        .HasColumnType("int");

                    b.Property<float?>("PCompra")
                        .HasColumnType("real");

                    b.Property<float?>("PVenta")
                        .HasColumnType("real");

                    b.Property<float?>("Precio")
                        .HasColumnType("real");

                    b.Property<float?>("PrecioA")
                        .HasColumnType("real");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("VarPorcentual")
                        .HasColumnType("real");

                    b.Property<string>("VolNom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrecioId");

                    b.ToTable("CotizacionAccion");
                });
#pragma warning restore 612, 618
        }
    }
}
