// <auto-generated />
using System;
using MercadoCapitales.API.Precios.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Precios.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250121114910_VERSION0")]
    partial class VERSION0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.MarketData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ACP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EV")
                        .HasColumnType("int");

                    b.Property<decimal?>("HI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NV")
                        .HasColumnType("int");

                    b.Property<decimal?>("OP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TV")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MarketData");
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.OpenInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId")
                        .IsUnique();

                    b.ToTable("OpenInterests");
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId")
                        .IsUnique();

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Bid", b =>
                {
                    b.HasOne("MercadoCapitales.API.Precios.Models.MarketData", "MarketData")
                        .WithMany("BI")
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Offer", b =>
                {
                    b.HasOne("MercadoCapitales.API.Precios.Models.MarketData", "MarketData")
                        .WithMany("OF")
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.OpenInterest", b =>
                {
                    b.HasOne("MercadoCapitales.API.Precios.Models.MarketData", "MarketData")
                        .WithOne("OI")
                        .HasForeignKey("MercadoCapitales.API.Precios.Models.OpenInterest", "MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercadoCapitales.API.Precios.Models.Settlement", b =>
                {
                    b.HasOne("MercadoCapitales.API.Precios.Models.MarketData", "MarketData")
                        .WithOne("SE")
                        .HasForeignKey("MercadoCapitales.API.Precios.Models.Settlement", "MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
