// <auto-generated />
using System;
using MercadoCapitales.API.Ordenes.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Ordenes.Migrations
{
    [DbContext(typeof(ContextOrden))]
    [Migration("20221229143710_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Ordenes.Modelo.Orden", b =>
                {
                    b.Property<Guid?>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Cantidad")
                        .HasColumnType("real");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComitenteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<float>("Importe")
                        .HasColumnType("real");

                    b.Property<string>("OrdenCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plazo")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCompraVenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValidezOferta")
                        .HasColumnType("int");

                    b.HasKey("OrdenId");

                    b.ToTable("Orden");
                });
#pragma warning restore 612, 618
        }
    }
}
