// <auto-generated />
using System;
using MercadoCapitales.API.Ordenes.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoCapitales.API.Ordenes.Migrations
{
    [DbContext(typeof(ContextOrden))]
    [Migration("20241210182459_VERSION2")]
    partial class VERSION2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercadoCapitales.API.Ordenes.Modelo.InstrumentId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstrumentId");
                });

            modelBuilder.Entity("MercadoCapitales.API.Ordenes.Modelo.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CancelPrevious")
                        .HasColumnType("bit");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DisplayQuantity")
                        .HasColumnType("bigint");

                    b.Property<int>("Expiration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Iceberg")
                        .HasColumnType("bit");

                    b.Property<Guid?>("InstrumentIdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proprietary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentIdId");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("MercadoCapitales.API.Ordenes.Modelo.Orden", b =>
                {
                    b.HasOne("MercadoCapitales.API.Ordenes.Modelo.InstrumentId", "InstrumentId")
                        .WithMany()
                        .HasForeignKey("InstrumentIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
